name: Deploy With CDK
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  run-cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20

      - name: Setup Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Use nix-develop shell
        uses: nicknovitski/nix-develop@v1.2.1
        with:
          arguments: . --impure --accept-flake-config

      - name: Add the arm targets
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          aws-region: us-west-2
          role-duration-seconds: 900

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install deps
        working-directory: ./cdk
        run: |
          pnpm install

      - name: cdk deploy
        working-directory: ./cdk
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          pnpm run deploy
