name: Rust

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
<<<<<<< Updated upstream
        working-directory: ./trashcal-lambda
        run: cargo build --verbose
||||||| Stash base
        run: cargo build --verbose
=======
        run: devenv shell cargo lambda build --arm64
>>>>>>> Stashed changes

      - name: Run tests
<<<<<<< Updated upstream
        working-directory: ./trashcal-lambda
        run: cargo test --verbose
||||||| Stash base
        run: cargo test --verbose
=======
        run: devenv shell cargo test
>>>>>>> Stashed changes
