name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Use nix-develop shell
        uses: nicknovitski/nix-develop@v1.1.0
        with:
          arguments: . --impure

      - name: Rust Targets
        run: rustup target list --installed

      - name: Build
        working-directory: ./trashcal-lambda
        run: cargo lambda build --arm64

      - name: Run tests
        working-directory: ./trashcal-lambda
        run: cargo test
