name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: devenv shell bash -- -e {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Set up devenv cache
        uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv
        shell: bash
        run: nix profile add nixpkgs#devenv

      - name: Build
        run: cd trashcal-lambda && cargo lambda build --arm64

      - name: Run tests
        run: cd trashcal-lambda && cargo test
