name: Rust

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      
      - name: Nix Develop Action
        uses: nicknovitski/nix-develop@v1.1.0
      
      - name: Build
        working-directory: ./trashcal-lambda
        run: cargo lambda build --arm64

      - name: Run tests
        working-directory: ./trashcal-lambda
        run: cargo test
